# Generated by Django 2.2 on 2019-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, choices=[('Bedsitter', 'Bedsitter'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('Shop', 'Shop')], max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
